
service: dinner-project

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
  deploymentBucket: ${file(./config.js):config.BUCKET_NAME}
  deploymentPrefix: ${self:service}
  role: arn:aws:iam::${file(./config.js):config.ACCOUNT_NUM}:role/${file(./config.js):config.ROLE_NAME}
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  hello:
    handler: handler.hello
    events: 
      - http:
          path: hello
          method: get
      - cloudwatchLog: '/aws/lambda/${self:service}'